name: flutter_nb_net

description: |
  A powerful HTTP package for Dart/Flutter,base on dio.
  which supports Global settings, Interceptors,
  FormData, Aborting and canceling a request,
  Files uploading and downloading,
  Requests timeout, Custom adapters, etc.

version: 2.0.3
homepage: https://github.com/yuexunshi/flutter_net

environment:
  sdk: '>=2.19.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  freezed_annotation: ^3.1.0
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

